[workspace]
resolver = "2"
members = [
    "aln-coord",
    "aln-core",
    "aln-engine",
    "aln-parasail",
    "aln-rmblast",
    "aln-rmblastn",
    "aln-reference",
    "dfam-stk-io",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
license = "CC0-1.0"
repository = "https://github.com/Dfam-consortium/dfam-lib"

[workspace.dependencies]
aln-coord = { path = "aln-coord" }
aln-core = { path = "aln-core" }
aln-engine = { path = "aln-engine" }
aln-parasail = { path = "aln-parasail" }
aln-rmblast = { path = "aln-rmblast" }
aln-rmblastn = { path = "aln-rmblastn" }
aln-reference = { path = "aln-reference" }
dfam-stk-io = { path = "dfam-stk-io" }

thiserror = "2"
rayon = "1"

[profile.release]
opt-level = 3
lto = "thin"
