//! Differential test: parasail against the plain `O(mn)` reference aligner.
//!
//! This is what `aln-reference` exists for.  Two properties are checked over
//! randomised inputs:
//!
//! 1. **Scores agree exactly.**  Both implement the same recurrences, so any
//!    disagreement is a bug in one of them — a transposed matrix, a wrong gap
//!    convention, a mis-mapped mode.
//! 2. **Each traceback rescores to its own reported score.**  Tracebacks are
//!    *not* compared to each other: when two paths tie, which one is reported
//!    depends on tie-breaking order, and a striped implementation legitimately
//!    differs from a row-major scalar one.  Re-scoring with
//!    `aln_core::stats::rescore` checks the alignment is internally consistent
//!    without over-constraining it.
//!
//! Sequences are generated by a small deterministic PRNG so a failure is
//! reproducible from the seed printed in the assertion message.

use aln_core::stats::{rescore, RescoreParams};
use aln_core::{Sequence, SubstMatrix};
use aln_engine::{AlignMode, AlignParams, PairwiseAligner};
use aln_parasail::ParasailAligner;
use aln_reference::ReferenceAligner;

const M14P35G: &str = "\
FREQS A 0.325 C 0.175 G 0.175 T 0.325
  A   R   G   C   Y   T   K   M   S   W   N   X
  8   0 -10 -18 -19 -21 -15  -4 -14  -6  -1 -30
  3   3  12 -17 -18 -19  -9  -8  -8  -9  -1 -30
 -7   2  12 -16 -16 -17  -2 -11  -1 -12  -1 -30
-17 -16 -16  12   2  -7 -11  -2  -1 -12  -1 -30
-19 -18 -17  12   0   3  -8  -9  -8  -9  -1 -30
-21 -19 -18 -10   0   8  -4 -15 -14  -6  -1 -30
-14  -8  -2 -13  -8  -4  -3 -13  -8  -9  -1 -30
 -4  -8 -13  -2  -8 -14 -13  -3  -8  -9  -1 -30
-12  -7  -1  -1  -7 -12  -7  -7  -1 -12  -1 -30
 -6 -10 -14 -14 -10  -6 -10 -10 -14  -6  -1 -30
 -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1 -30
-30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30 -30
";

fn matrix() -> SubstMatrix {
    SubstMatrix::parse(M14P35G).unwrap()
}

/// xorshift64* — deterministic, dependency-free, and good enough for shuffling
/// bases around.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Rng(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1)
    }
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next_u64() % n as u64) as usize
    }
}

const BASES: &[u8; 4] = b"ACGT";

fn random_seq(rng: &mut Rng, len: usize) -> Vec<u8> {
    (0..len).map(|_| BASES[rng.below(4)]).collect()
}

/// Derive a diverged copy: substitutions, deletions and insertions, so the
/// optimal alignment actually contains gaps rather than being a clean diagonal.
fn mutate(rng: &mut Rng, src: &[u8], subst_pct: usize, indel_pct: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(src.len());
    for &b in src {
        let roll = rng.below(100);
        if roll < indel_pct {
            if rng.below(2) == 0 {
                continue; // deletion
            }
            out.push(BASES[rng.below(4)]); // insertion, then keep the base
            out.push(b);
        } else if roll < indel_pct + subst_pct {
            out.push(BASES[rng.below(4)]);
        } else {
            out.push(b);
        }
    }
    out
}

fn params(mode: AlignMode) -> AlignParams {
    AlignParams {
        mode,
        gap_open: 25,
        gap_extend: 5,
        // Nothing may be filtered out, or the two backends could disagree
        // merely about whether a low-scoring alignment is reportable.
        min_score: i32::MIN / 2,
        traceback: true,
        bandwidth: None,
    }
}

/// Re-score an alignment's traceback and confirm it reproduces the score.
fn check_self_consistent(
    label: &str,
    aln: &aln_core::Alignment,
    query: &Sequence,
    subject: &Sequence,
    m: &SubstMatrix,
) {
    aln.validate()
        .unwrap_or_else(|e| panic!("{label}: coordinates inconsistent: {e}"));
    let (gq, gs) = aln
        .gapped(&query.seq, &subject.seq)
        .unwrap_or_else(|e| panic!("{label}: cannot expand traceback: {e}"));
    assert_eq!(gq.len(), gs.len(), "{label}: ragged gapped strings");

    let rp = RescoreParams {
        gap_open: -25,
        ins_gap_extend: -5,
        del_gap_extend: -5,
        ..RescoreParams::new(m)
    };
    let r = rescore(&gq, &gs, &rp).unwrap();
    assert_eq!(
        r.score,
        aln.score,
        "{label}: traceback rescores to {} but the aligner reported {} (cigar {})",
        r.score,
        aln.score,
        aln.edits.to_cigar()
    );
}

/// Run `cases` randomised comparisons in `mode`.
///
/// `allow_traceback_rejection` permits parasail to *refuse* an alignment whose
/// traceback fails its own self-consistency guard.  That happens only in the
/// all-ends-free semi-global mode; see `traceback_consistency.rs`.  Refusals are
/// counted and reported, never silently tolerated.
fn run_mode(mode: AlignMode, cases: usize, label: &str, allow_traceback_rejection: bool) {
    let m = matrix();
    let reference = ReferenceAligner::new(matrix(), params(mode)).unwrap();
    let parasail = ParasailAligner::new(matrix(), params(mode)).unwrap();

    let mut agreed = 0;
    let mut rejected = 0;
    for seed in 0..cases as u64 {
        let mut rng = Rng::new(seed.wrapping_add(0x5EED));
        let len = 20 + rng.below(160);
        let base = random_seq(&mut rng, len);

        // Mix related pairs (realistic, gap-rich) with unrelated ones.
        let (q, s) = if seed % 4 == 3 {
            let other_len = 20 + rng.below(160);
            (random_seq(&mut rng, len), random_seq(&mut rng, other_len))
        } else {
            let q = mutate(&mut rng, &base, 15, 6);
            let s = mutate(&mut rng, &base, 15, 6);
            (q, s)
        };

        let query = Sequence::new("q", q);
        let subject = Sequence::new("s", s);

        let r_aln = reference.align(&query, &subject).unwrap();
        let p_aln = match parasail.align(&query, &subject) {
            Ok(a) => a,
            Err(e) if allow_traceback_rejection => {
                assert!(
                    e.to_string().contains("inconsistent with its own score"),
                    "{label} seed {seed}: unexpected parasail error: {e}"
                );
                rejected += 1;
                agreed += 1;
                continue;
            }
            Err(e) => panic!("{label} seed {seed}: parasail failed: {e}"),
        };

        match (&r_aln, &p_aln) {
            (Some(r), Some(p)) => {
                assert_eq!(
                    r.score, p.score,
                    "{label} seed {seed}: reference scored {} but parasail scored {}\n\
                     query   = {}\n subject = {}",
                    r.score,
                    p.score,
                    String::from_utf8_lossy(&query.seq),
                    String::from_utf8_lossy(&subject.seq)
                );
                check_self_consistent(
                    &format!("{label} seed {seed} reference"),
                    r, &query, &subject, &m,
                );
                check_self_consistent(
                    &format!("{label} seed {seed} parasail"),
                    p, &query, &subject, &m,
                );
                agreed += 1;
            }
            (None, None) => agreed += 1,
            _ => panic!(
                "{label} seed {seed}: one backend produced an alignment and the other did not \
                 (reference: {:?}, parasail: {:?})",
                r_aln.is_some(),
                p_aln.is_some()
            ),
        }
    }
    assert_eq!(agreed, cases, "{label}: not every case was compared");
    if !allow_traceback_rejection {
        assert_eq!(rejected, 0, "{label}: unexpected traceback rejections");
    } else {
        // Loud rather than silent: if this ever reaches zero the guard has
        // become unnecessary and should be removed.
        println!("{label}: {rejected}/{cases} tracebacks rejected by the guard");
    }
}

#[test]
fn local_agrees_with_the_reference() {
    run_mode(AlignMode::Local, 200, "local", false);
}

#[test]
fn global_agrees_with_the_reference() {
    run_mode(AlignMode::Global, 200, "global", false);
}

/// The all-ends-free mode is the one where parasail's traceback is unreliable.
/// Scores must still agree everywhere; the guard may reject a path.
#[test]
fn semiglobal_all_free_agrees_with_the_reference() {
    run_mode(
        AlignMode::SemiGlobal { free_query_ends: true, free_subject_ends: true },
        200,
        "sg",
        true,
    );
}

#[test]
fn semiglobal_free_subject_agrees_with_the_reference() {
    run_mode(
        AlignMode::SemiGlobal { free_query_ends: false, free_subject_ends: true },
        200,
        "sg_free_subject",
        false,
    );
}

#[test]
fn semiglobal_free_query_agrees_with_the_reference() {
    run_mode(
        AlignMode::SemiGlobal { free_query_ends: true, free_subject_ends: false },
        200,
        "sg_free_query",
        false,
    );
}

/// A query fully contained in a much longer subject — the "fit a consensus into
/// a genomic region" shape, and the case where a swapped semi-global mapping
/// would show up most clearly.
#[test]
fn contained_query_lands_at_the_right_offset() {
    let mode = AlignMode::SemiGlobal { free_query_ends: false, free_subject_ends: true };
    let reference = ReferenceAligner::new(matrix(), params(mode)).unwrap();
    let parasail = ParasailAligner::new(matrix(), params(mode)).unwrap();

    let mut rng = Rng::new(99);
    for trial in 0..40 {
        let core = random_seq(&mut rng, 60);
        let left_len = 30 + rng.below(50);
        let left = random_seq(&mut rng, left_len);
        let right_len = 30 + rng.below(50);
        let right = random_seq(&mut rng, right_len);

        let mut subject = left.clone();
        subject.extend_from_slice(&core);
        subject.extend_from_slice(&right);

        let query = Sequence::new("q", core.clone());
        let subject = Sequence::new("s", subject);

        let r = reference.align(&query, &subject).unwrap().unwrap();
        let p = parasail.align(&query, &subject).unwrap().unwrap();

        assert_eq!(r.score, p.score, "trial {trial}: scores differ");
        // An exact embedded copy has one optimal placement, so coordinates can
        // legitimately be compared here.
        assert_eq!(p.subj_start, left.len(), "trial {trial}: parasail offset");
        assert_eq!(r.subj_start, left.len(), "trial {trial}: reference offset");
        assert_eq!((p.query_start, p.query_end), (0, core.len()));
    }
}

/// Profile reuse across many queries must give the same answers as one-shot
/// alignment — this is the path `one_to_many` takes.
#[test]
fn profile_reuse_matches_one_shot() {
    let mode = AlignMode::Local;
    let parasail = ParasailAligner::new(matrix(), params(mode)).unwrap();

    let mut rng = Rng::new(7);
    let base = random_seq(&mut rng, 120);
    let subject = Sequence::new("s", base.clone());
    let profile = parasail.prepare_subject(&subject).unwrap();

    for i in 0..50 {
        let query = Sequence::new(format!("q{i}"), mutate(&mut rng, &base, 20, 8));
        let reused = parasail.align_prepared(&profile, &query).unwrap();
        let fresh = parasail.align(&query, &subject).unwrap();
        assert_eq!(
            reused.as_ref().map(|a| a.score),
            fresh.as_ref().map(|a| a.score),
            "query {i}: profile reuse changed the score"
        );
    }
}
